#!/bin/bash

WRAPPER_PATH=/usr/bin/chromium

cat > "$WRAPPER_PATH" <<_EOF
#!/bin/bash
# Note: exec -a below is a bashism.
exec -a "\$0" "/usr/bin/chromium-browser" --no-sandbox "\$@"
_EOF
chmod +x "$WRAPPER_PATH"
